jobs_page = 'https://www.linkedin.com/jobs/search/?currentJobId=3924092230&keywords=data%20scientist&location=Pakistan&origin=JOBS_HOME_KEYWORD_AUTOCOMPLETE&refresh=true'
my_email = 'YOUR_EMAIL_ID'
password = 'YOUR_LINKDIN_PASSWORD'
login_page = 'https://www.linkedin.com/login?fromSignIn=true&trk=guest_homepage-basic_nav-header-signin'
job_details_page = 'https://www.linkedin.com/jobs/search/?currentJobId='
